### ISSUE TITLE
Last line in qrg.txt can´t be configured.

### ISSUE THREAD

**Issue by beliffm** [dl9rdz/rdz_ttgo_sonde#93] opened 2021-06-22 20:14 UTC
If the MAXSONDE parameter is set to n, only n-1 sondes can be configured. The last line always stays with 400.000 MHz regardless of any attempt to change it.

73s Bernd, DL1ZP

**Comment by beliffm** [comment] 2021-07-30 14:00
Just wondering. Did I step on someones foot?

**Comment by dl9rdz** [comment] 2021-08-06 14:15
No, thanks for the report.

"Its not a bug, it is just an unimplemented feature".  One entry was (long time ago) intended to be an entry to be changed dynamically (scanning, or some key presses to go up/down, or to copy peak from scanner, etc.). Has never been implemented, and is not intuitive, so I guess I should change it in the future.

**Comment by beliffm** [comment] 2021-08-06 16:58
Thanks for the update, i appreciate it.

**Comment by dl9rdz** [comment] 2021-08-06 20:27
In the latest version, this should be fixed now.

**Closed by dl9rdz** 2021-08-06 20:27 UTC
